#!/usr/bin/env bash
# install-git-hooks — wire repo-local pre-commit hooks into .git/hooks/.
# Run once after cloning: `bash scripts/install-git-hooks.sh`.
#
# Currently installs:
#   iron-gate-precommit — refuses removal of IRON GATE sentinels without override.
#
# If .git/hooks/pre-commit already exists, this script chains the gate check
# onto the existing hook rather than overwriting it.

set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"
HOOK_DIR="$REPO_ROOT/.git/hooks"
HOOK="$HOOK_DIR/pre-commit"
GATE_SCRIPT="$REPO_ROOT/scripts/iron-gate-precommit.sh"

if [ ! -f "$GATE_SCRIPT" ]; then
  echo "✗ missing $GATE_SCRIPT — bad checkout?" >&2
  exit 1
fi

mkdir -p "$HOOK_DIR"

# Case 1 — no existing hook: write a thin wrapper that calls our gate check.
if [ ! -f "$HOOK" ]; then
  cat > "$HOOK" <<EOF
#!/usr/bin/env bash
# auto-generated by scripts/install-git-hooks.sh
exec "$GATE_SCRIPT" "\$@"
EOF
  chmod +x "$HOOK"
  echo "✓ installed pre-commit hook → $HOOK"
  exit 0
fi

# Case 2 — already installed by us: refresh + done.
if grep -q "iron-gate-precommit" "$HOOK"; then
  echo "✓ iron-gate pre-commit already installed (no change)"
  exit 0
fi

# Case 3 — pre-existing hook from another source: chain ours after it.
echo "→ found existing pre-commit hook; chaining iron-gate check after it"
cat >> "$HOOK" <<EOF

# === iron-gate-precommit (added by scripts/install-git-hooks.sh) ===
"$GATE_SCRIPT" "\$@"
EOF
echo "✓ chained iron-gate check onto $HOOK"
