#!/usr/bin/env bash
# IRON GATE for BUG-015 — JWT signature mismatch regression check.
#
# Fails (non-zero exit) if any of the following silent-regression conditions
# would prevent the local backend from verifying the production keychain JWT:
#
#   A. ~/.claude-credentials/junior-jwt.env was NOT sourced into the running
#      backend (env vars JWT_PRIVATE_PEM / JWT_PUBLIC_PEM not loaded).
#   B. The backend is serving an autogenerated keypair (.junior-keys/*.pem)
#      instead of the production rotated-2026-05-24 keypair.
#   C. /me with the keychain LICENSE_JWT does not return HTTP 200.
#
# Run this before claiming a backend restart is "good" for D1 / desktop dev.
#
# Read-only: no env mutation, no key writes, no DB writes, no HTTP POSTs.
#
# Exit codes:
#   0  all checks passed
#   1  keychain JWT missing or malformed
#   2  prod env file missing or malformed
#   3  backend not reachable at the expected URL
#   4  backend public key does not match prod public key
#   5  /me did not return 200

set -u

BACKEND_URL="${JUNIOR_BACKEND_URL:-http://127.0.0.1:8000}"
ENV_FILE="${HOME}/.claude-credentials/junior-jwt.env"
KEYCHAIN_SVC="app.liquidclips.auth.v1"
KEYCHAIN_ACCT="LICENSE_JWT"

red()   { printf "\033[31m%s\033[0m\n" "$*"; }
green() { printf "\033[32m%s\033[0m\n" "$*"; }
dim()   { printf "\033[2m%s\033[0m\n" "$*"; }

fail() {
  red "IRON GATE BUG-015 — FAIL: $1"
  shift
  for line in "$@"; do dim "  $line"; done
  exit "${LAST_CODE:-1}"
}

# --- step 1: keychain JWT ---
JWT="$(security find-generic-password -s "$KEYCHAIN_SVC" -a "$KEYCHAIN_ACCT" -w 2>/dev/null)"
if [ -z "$JWT" ] || [ "${JWT:0:2}" != "ey" ]; then
  LAST_CODE=1 fail "Keychain LICENSE_JWT missing or not a JWT." \
    "service=${KEYCHAIN_SVC} acct=${KEYCHAIN_ACCT}" \
    "Re-activate the desktop app to mint a fresh JWT, or restore the keychain entry."
fi

# --- step 2: prod public PEM (from env file) ---
if [ ! -f "$ENV_FILE" ]; then
  LAST_CODE=2 fail "Production JWT env file not found: $ENV_FILE" \
    "Restore it from 1Password / Railway env mirror before re-running the backend."
fi
PROD_PUB="$(awk '/JWT_PUBLIC_PEM=/{flag=1} flag{print} /END PUBLIC KEY-----/{exit}' "$ENV_FILE" \
  | sed -e 's/^JWT_PUBLIC_PEM=//' -e 's/^"//' -e 's/"$//' -e 's/^export //' \
  | tr -d '"' | sed 's/\\n/\n/g')"
if ! printf '%s' "$PROD_PUB" | grep -q "BEGIN PUBLIC KEY"; then
  LAST_CODE=2 fail "Could not extract JWT_PUBLIC_PEM from $ENV_FILE" \
    "The env file format may have drifted. Expected: export JWT_PUBLIC_PEM=\"<PEM>\""
fi

# --- step 3: backend public PEM (live) ---
# curl writes body to file, prints code to stdout — sidesteps macOS head/tail
# limits and avoids parsing a body+marker concatenation.
BACKEND_HTTP="$(curl -sS -m 5 -o /tmp/iron-gate-bug-015-pub.json \
  -w "%{http_code}" "$BACKEND_URL/desktop/public-key" 2>&1)" || true
if [ "$BACKEND_HTTP" != "200" ]; then
  LAST_CODE=3 fail "Backend /desktop/public-key did not return 200 (got $BACKEND_HTTP)." \
    "Backend URL: $BACKEND_URL" \
    "Is the local junior-backend running on this port?"
fi
BACKEND_PUB="$(python3 -c 'import json,sys; print(json.load(open("/tmp/iron-gate-bug-015-pub.json"))["public_pem"], end="")')"
if ! printf '%s' "$BACKEND_PUB" | grep -q "BEGIN PUBLIC KEY"; then
  LAST_CODE=3 fail "Backend /desktop/public-key returned a malformed body." \
    "Body: $BACKEND_PUB_JSON"
fi

# --- step 4: prod-pub vs backend-pub equality ---
PROD_BODY="$(printf '%s' "$PROD_PUB"    | grep -v 'PUBLIC KEY-----' | tr -d '\n\r ')"
BACK_BODY="$(printf '%s' "$BACKEND_PUB" | grep -v 'PUBLIC KEY-----' | tr -d '\n\r ')"
if [ "$PROD_BODY" != "$BACK_BODY" ]; then
  AUTOGEN_FILE="/Users/dipdip/code/jnr/junior-backend/.junior-keys/public.pem"
  AUTOGEN_HINT=""
  if [ -f "$AUTOGEN_FILE" ]; then
    AUTOGEN_BODY="$(grep -v 'PUBLIC KEY-----' "$AUTOGEN_FILE" | tr -d '\n\r ')"
    if [ "$AUTOGEN_BODY" = "$BACK_BODY" ]; then
      AUTOGEN_HINT="Backend is serving the AUTOGENERATED keypair at .junior-keys/ — junior-jwt.env was NOT sourced before uvicorn."
    fi
  fi
  LAST_CODE=4 fail "Backend public key does NOT match prod public key — autogen-fallback regression." \
    "Prod    pub fingerprint: ${PROD_BODY:0:32}…" \
    "Backend pub fingerprint: ${BACK_BODY:0:32}…" \
    "$AUTOGEN_HINT" \
    "Fix: kill backend, then 'set -a; source ~/.claude-credentials/junior-jwt.env; source ~/.claude-credentials/openai.env; set +a; ./.venv/bin/uvicorn app.main:app --port 8000'"
fi

# --- step 5: /me with the keychain JWT ---
ME_HTTP="$(curl -sS -m 5 -o /tmp/iron-gate-bug-015-me.json -w "%{http_code}" \
  -H "Authorization: Bearer $JWT" "$BACKEND_URL/me" 2>&1)"
if [ "$ME_HTTP" != "200" ]; then
  ME_BODY="$(cat /tmp/iron-gate-bug-015-me.json 2>/dev/null | head -c 240)"
  LAST_CODE=5 fail "/me with keychain JWT did not return 200 (got $ME_HTTP)." \
    "Body: $ME_BODY" \
    "Signature gate passed but user lookup failed. Seed the local DB user row for sub=$(printf '%s' "$JWT" | cut -d. -f2 | base64 -d 2>/dev/null | python3 -c 'import sys,json; print(json.load(sys.stdin).get("sub","?")[:12])' 2>/dev/null)…"
fi

# --- all green ---
green "IRON GATE BUG-015 — PASS"
dim   "  backend:     $BACKEND_URL"
dim   "  pub-key:     prod == backend ($BACKEND_HTTP)"
dim   "  /me:         HTTP 200"
dim   "  JWT source:  keychain $KEYCHAIN_SVC/$KEYCHAIN_ACCT"
exit 0
