// Liquid Clips 2.0 — typed flow registry.
// One source of truth for every Flow ID. Flow IDs are immutable contract
// names referenced by the dependency map, phase gates, and contract docs in
// docs/lc2/CONTRACTS/FLOWS/.

export const FLOW_IDS = {
  FLOW_000_APP_SHELL: "FLOW_000_APP_SHELL",
  FLOW_001_CREATE_URL_TO_CLIPS: "FLOW_001_CREATE_URL_TO_CLIPS",
  FLOW_002_CREATE_IMPORT_TO_CLIPS: "FLOW_002_CREATE_IMPORT_TO_CLIPS",
  FLOW_003_EDITOR_PREVIEW: "FLOW_003_EDITOR_PREVIEW",
  FLOW_004_FREE_WATERMARK_EXPORT: "FLOW_004_FREE_WATERMARK_EXPORT",
  FLOW_005_PAID_NO_WATERMARK_EXPORT: "FLOW_005_PAID_NO_WATERMARK_EXPORT",
  FLOW_006_PROJECTS_CREATE_ADD_MOVE: "FLOW_006_PROJECTS_CREATE_ADD_MOVE",
  FLOW_007_SCHEDULE_CHANNELS_STATE: "FLOW_007_SCHEDULE_CHANNELS_STATE",
  FLOW_008_SOCIAL_AUTH_RETURN_TO_APP: "FLOW_008_SOCIAL_AUTH_RETURN_TO_APP",
  FLOW_009_PUBLISH_PLATFORM_SELECT: "FLOW_009_PUBLISH_PLATFORM_SELECT",
  FLOW_010_COMMUNITY_OPEN_JOIN_RETURN: "FLOW_010_COMMUNITY_OPEN_JOIN_RETURN",
  FLOW_011_EARN_MISSIONS_REWARDS: "FLOW_011_EARN_MISSIONS_REWARDS",
  FLOW_012_SETTINGS_NO_PASSIVE_KEYCHAIN: "FLOW_012_SETTINGS_NO_PASSIVE_KEYCHAIN",
  FLOW_013_HQ_WEBSITE_DEEP_LINK_HANDOFF: "FLOW_013_HQ_WEBSITE_DEEP_LINK_HANDOFF",
  FLOW_014_DIAGNOSTICS_HEALTH_REPORT: "FLOW_014_DIAGNOSTICS_HEALTH_REPORT",
  FLOW_015_BROWSE_YOUTUBE_DRIVE_IMPORT: "FLOW_015_BROWSE_YOUTUBE_DRIVE_IMPORT",
  FLOW_016_CAMPAIGN_CREATE: "FLOW_016_CAMPAIGN_CREATE",
  FLOW_017_CLIPPER_JOIN_CAMPAIGN: "FLOW_017_CLIPPER_JOIN_CAMPAIGN",
  FLOW_018_WATERMARK_COMPOSER: "FLOW_018_WATERMARK_COMPOSER",
  FLOW_019_WHOP_REWARDS_HANDOFF: "FLOW_019_WHOP_REWARDS_HANDOFF",
  FLOW_020_AYRSHARE_PUBLISH_HANDOFF: "FLOW_020_AYRSHARE_PUBLISH_HANDOFF",
  FLOW_021_ENTITLEMENT_REFRESH: "FLOW_021_ENTITLEMENT_REFRESH",
  FLOW_022_REWARDS_RETURN: "FLOW_022_REWARDS_RETURN",
} as const;

export type FlowId = (typeof FLOW_IDS)[keyof typeof FLOW_IDS];

export const ALL_FLOW_IDS: FlowId[] = Object.values(FLOW_IDS);
